id: A9B194334
title: Toh_178-Teaching_on_the_Aids_to_Enlightenment-v2
type: translation
pechas:
- I4DABB266
- IA97F997F
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-060-007
  title: Toh_178-Teaching_on_the_Aids_to_Enlightenment-v2
alignment_to_base:
  I4DABB266/ACC4: 412C
  IA97F997F/B489: 412C
